# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test-controller
      - uses: actions/upload-artifact@v4  # upload test results
        name: Upload artifacts
        if: ${{ !cancelled() }} 
        with:
          name: test-controller-results
          path: report/test-results.json

      - uses: dorny/test-reporter@v2
        name: Publish test results
        with:
          artifact: test-controller-results           
          name: Mocha Tests                 
          path: 'test-results.json'    
          reporter: mocha-json      

      - run: npm run start:rest &
      - run: sleep 5
      - run: npm run test-external
      - uses: actions/upload-artifact@v4  # upload test results
        name: Upload artifacts
        if: ${{ !cancelled() }} 
        with:
          name: test-external-results
          path: report/test-results.json

      - uses: dorny/test-reporter@v2
        name: Publish test results
        with:
          artifact: test-external-results            
          name: Mocha Tests                 
          path: 'test-results.json'    
          reporter: mocha-json      

      - run: npm run start:graphql &
      - run: sleep 5
      - run: npm run test-external-graphql
      - uses: actions/upload-artifact@v4  # upload test results
        name: Upload artifacts
        if: ${{ !cancelled() }} 
        with:
          name: test-graphql-external-results
          path: report/test-results.json

      - uses: dorny/test-reporter@v2
        name: Publish test results
        with:
          artifact: test-graphql-external-results          
          name: Mocha Tests                 
          path: 'test-results.json'    
          reporter: mocha-json

      - uses: grafana/setup-k6-action@v1
        name: Setup K6

      - uses: grafana/run-k6-action@v1
        id: run_k6
        name: Run k6 test
        env:
          BASE_URL: ${{ secrets.BASE_URL}}
        with:
          path: ./tests/k6/*.test.js
          cloud-run-locally: false
          cloud-comment-on-pr: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Directory containing the static site files
          path: 'report/k6-result.html'
      
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4